# Generated by Django 4.2.5 on 2023-09-23 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='image',
            field=models.ImageField(default='user/test.jpg', upload_to='user/'),
        ),
    ]
