# Generated by Django 4.2.5 on 2023-09-23 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_coupon_news_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.ImageField(default='media/logo.jpgs', upload_to='media/'),
        ),
    ]
