# Generated by Django 4.2.5 on 2023-09-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_news_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='image',
            field=models.ImageField(default='media/logo.jpgs', upload_to='media/'),
        ),
    ]
