# Generated by Django 4.2.5 on 2023-09-23 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_provider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='/media/logo.jpgs', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='image',
            field=models.ImageField(default='/media/logo.jpgs', upload_to='media/'),
        ),
    ]
