# Generated by Django 4.2.5 on 2023-09-23 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_news_image_alter_provider_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='media/logo.jpg', upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='image',
            field=models.ImageField(default='media/logo.jpg', upload_to='media/'),
        ),
    ]
