# Generated by Django 4.2.5 on 2023-09-23 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_alter_news_image_alter_provider_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='image',
        ),
    ]
