# Generated by Django 4.2.5 on 2023-09-23 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_news_summary_alter_news_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(default='user/test.jpg', upload_to='user/'),
        ),
    ]
