# Generated by Django 4.2.6 on 2023-10-21 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_review_rate_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='user/test.jpg', upload_to='user/'),
        ),
    ]
